### ISSUE TITLE
what "nominations" are on nominated target page unclear

### ISSUE THREAD

**Issue by blogsdon** [Sage-Bionetworks/Agora#225]

**Comment by annagree** [comment]
Change name in raw data. From Nominations to "Number of Nominations".

**Comment by kdaily** [comment]
After some thought this isn't the best approach. It doesn't require a change to data, and since redeployment is required we should avoid if possible.

@Zaknarfen what kind of structure would you propose to map keys/columns from the data to user friendly names? E.g. now the JSON for nominated targets has `nominations`, but what we mean is `Number of Nominations`, and we want that to show in the column of the table.

**Comment by Zaknarfen** [comment]
There are two problems with `# of Nominations` or `Number of Nominations`. One is that we are using a component from PrimeNG for the table. That means we can't just change the header in a smaller screen, we would need some logic based on the screen size and that header text variable inside `PrimeNG` component. The second problem is that the text can't be big for mobile so... it would be good to come up with a new expression perhaps. Can we call it `Studies`? or `Researches`? @kdaily. @annagree
