### ISSUE TITLE
move to elastic beanstalk and update to latest docker version

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#337]
@kdaily also file Jira issue on this

**Comment by annagree** [comment]
More detail, from #289 
1. Move our stack to AWS Elastic Beanstalk (probably can be done in different ways). That would mean changing from one EC2 instance with multiple containers to the same containers scaled in an Amazon ECS cluster in an Elastic Beanstalk environment. AWS would do the balancing for us (no scaling problems here). We would just need to see how that plays with Nginx, do we keep four applications per instance?

2. Keep our version or change to the latest Docker-compose version. This would mean a complete change in how we do everything in Docker, like networks, connections, volumes, deprecated stuff we rely on etc... I don't know if we need this just to add deploy and use Docker in swarm mode. When you run Docker in swarm mode you are trying to create, manage and automate the cluster itself (one step above compose, that only orchestrates containers in one stack), but... can we achieve the same thing with compose in AWS Elastic Beanstalk? probably. I am not convinced we need to update, here is a more complete answer.

**Comment by zaro0508** [comment]
Is this still applicable?  Aren't we going to deploy on ECS now?

**Comment by kdaily** [comment]
I thought ECS was a component of Elastic Beanstalk, but I may be wrong. According to the [EB docs](https://aws.amazon.com/elasticbeanstalk/details/) "AWS Elastic Beanstalk supports web applications written in many popular languages and frameworks." Specifically here:

https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_docker_ecs.html#create_deploy_docker_ecs_resources

"When you create an environment using the multicontainer Docker platform, Elastic Beanstalk automatically creates and configures several Amazon Elastic Container Service resources while building the environment in order to create the necessary containers on each Amazon EC2 instance."

**Comment by zaro0508** [comment]
This is done.  Elastic beanstalk is powering 3 environments/sites.
https://agora-develop.ampadscicomp.org
https://agora-staging.ampadscicomp.org
https://agora-prod.ampadscicomp.org
