### ISSUE TITLE
Differential Expression axes not scaling correctly

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#401]
In cases where the data point is extremely outside of the range, it is sometimes cut off.

<img width="455" alt="screen shot 2018-09-20 at 11 38 24 am" src="https://user-images.githubusercontent.com/40642407/45839618-ba9b7a00-bcc9-11e8-9832-b41f4728f4e4.png">

**Comment by Zaknarfen** [comment]
Can you tell me a gene where this happens @annagree?

**Comment by annagree** [comment]
@Zaknarfen Here is one example: VGF for "IFG" and the AD base statistical model: 
http://agora.ampadportal.org/genes/(genes-router:gene-details/ENSG00000128564)

Strangely it now looks a bit different from the example above, because in this case the axes are crossing in front of the red point:
<img width="438" alt="screen shot 2018-09-25 at 4 07 28 pm" src="https://user-images.githubusercontent.com/40642407/46048237-35570180-c0dd-11e8-8a73-d01a434f9e56.png">

**Comment by Zaknarfen** [comment]
Surprisingly the chart is behaving correctly, adjusting the Y-axis accordingly. The problem is that the red circle has a greater radius than the other dots that are not showing up. Usually, that is fine, but when it comes to values close to the edge of the chart, the red circle radius is too big for the elastic Y domain to accommodate. We can see the center of red the circle just fine always, but the end of the circle is clipped in certain occasions like this one.

I looked into this and found that the default `yRangePadding` for this chart is equal to `8` pixels. That means that `8` pixels from the lowest or highest value in the `Y` direction is the chart inner box limits. At that limit, we render the `X` axis. Our red circle radius is `13.6` pixels, so `5` pixels got clipped there. The problem is solved by increasing the `yRangePadding` to meet our red circle radius plus a safety margin (I added 10% extra padding). I also made sure that the inner box and red circle are rendered after the `X` axis is rendered (always rendered on top of it).

The result for `VGF` is this:

![image](https://user-images.githubusercontent.com/4223973/46109705-ce5a4b00-c1b7-11e8-8ac8-1fbe2d51f6c9.png)
