### ISSUE TITLE
unexpected error message when gene name not found

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#663]
See the attachment- I haven't seen this error message before. This was a case when the gene name was not found. I searched for TMEM16B, which is not in the database. 
<img width="1440" alt="screen shot 2019-02-26 at 10 21 58 am" src="https://user-images.githubusercontent.com/40642407/53424105-934f8400-39b0-11e9-9e93-02f84d739636.png">

**Comment by Zaknarfen** [comment]
We can modify the messages for each of the response status I guess. In this case, we had a [404](https://en.wikipedia.org/wiki/HTTP_404) for that gene. It means we could not find that resource, but the request itself was OK. That is the standard error handling, it won't redirect you to the not found page because we are not changing the url with this request.

**Comment by stockards** [comment]
@Zaknarfen Are we able to do an in line alert/error state? I'll come up w/ 2 examples and you can use what is feasible.

**Comment by stockards** [comment]
Hi @Zaknarfen @annagree , 

Ideally we should use the option where it appears in the Search Bar instead of the modal if possible. let me know what you think. 
![Home_ Search_ Gene not found](https://user-images.githubusercontent.com/38479289/54230252-4a74f080-44c3-11e9-8962-703e04c1bdbd.png)
![Home_ Second visit_ Gene not found](https://user-images.githubusercontent.com/38479289/54230253-4a74f080-44c3-11e9-840c-6a752b3ef540.png)

**Comment by annagree** [comment]
@stockards The real issue is usually that they are using the wrong name for a gene. Do you think it makes sense to make a suggestion like "No results found. Try searching by the Ensembl Gene ID."

**Comment by annagree** [comment]
(I also think having the error in the Search Bar is ideal.)

**Comment by stockards** [comment]
@annagree Hmm that could work! Do we want to include anything like "Check the spelling" or just leave it at Ensembl Gene ID"?

**Comment by annagree** [comment]
I think Ensembl Gene ID is probably simplest. Many genes have multiple names, but we only use the one "official" name. So they might be using an alias that we just don't index. The medium-term solution is to put those synonyms in and make them searchable!

**Comment by Zaknarfen** [comment]
I can try showing the message in the Search Bar. The synonyms should be added, yea.
